[programs.localnet]
samo_manager = "7W6cQN1gyokmJFDss6zez3CpjAyv5KqRYjPa7bUDEtqK"

[programs.devnet]
samo_manager = "7W6cQN1gyokmJFDss6zez3CpjAyv5KqRYjPa7bUDEtqK"

[programs.mainnet]
samo_manager = "7W6cQN1gyokmJFDss6zez3CpjAyv5KqRYjPa7bUDEtqK"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "/Users/sachin/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "/Users/sachin/.config/solana/id.json"

#[provider]
#cluster = "testnet"
#wallet = "/Users/sachin/.config/solana/id.json"
#
#[provider]
#cluster = "mainnet"
#wallet = "/Users/sachin/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
copy-idl = "mkdir -p app/src/idl && cp target/idl/samo_manager.json app/src/idl/samo_manager.json"
